tags: ['golang']
timeout: 180s

steps:
- name: 'gcr.io/cloud-builders/go:debian'
  id: 'gofmt'
  entrypoint: 'bash'
  args: ['-c', 'diff <(echo -n) <(gofmt -s -d $(find . -type f -name "*.go" -not -path "./_*"))']

- name: 'gcr.io/cloud-builders/go:debian'
  id: 'pilot build, amd64'
  waitFor: ['gofmt']
  env: ['GOARCH=amd64']
  args: ['build', '.', 'errors']
- name: 'gcr.io/cloud-builders/go:debian'
  id: 'pilot build, x86'
  waitFor: ['gofmt']
  env: ['GOARCH=386']
  args: ['build', '.', 'errors']

- name: 'gcr.io/cloud-builders/go:debian'
  id: 'test, amd64'
  waitFor: ['pilot build, amd64']
  env: ['GOARCH=amd64']
  args: ['test', '-v']
- name: 'gcr.io/cloud-builders/go:debian'
  id: 'test, x86'
  waitFor: ['pilot build, x86', 'test, amd64']
  env: ['GOARCH=386']
  args: ['test', '-v']

- name: 'gcr.io/blitznote/golang/ineffassign'
  volumes:
  - name: 'hides_third-party_source'
    path: '/workspace/gopath/pkg/mod'
  id: 'ineffassign'
  waitFor: ['test, amd64', 'test, x86']
  args: ['.']
- name: 'gcr.io/blitznote/golang/golint'
  volumes:
  - name: 'hides_third-party_source'
    path: '/workspace/gopath/pkg/mod'
  id: 'lint'
  waitFor: ['test, amd64', 'test, x86']
- name: 'gcr.io/cloud-builders/go:debian'
  id: 'vet'
  waitFor: ['test, amd64', 'test, x86']
  args: ['vet', '.']
